BEGIN;

-- Suppression des tables existantes pour éviter les conflits
DROP TABLE IF EXISTS "bar", "bubble_tea", "tea", "milk", "topping", "pearl", "collection";

-- Création de la table "bar"
CREATE TABLE "bar" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "adresse" text NOT NULL,
    "horaire" text NOT NULL,
    "image1" text,
    "image2" text,
    "image3" text,
    "image4" text,
    "image5" text,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- Création des tables de base sans dépendances
CREATE TABLE "tea" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "milk" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "topping" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "pearl" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- Création de la table "collection" sans la référence à "bubble_tea"
CREATE TABLE "collection" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "image_collection" text,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- Création de la table "bubble_tea" avec toutes ses références
CREATE TABLE "bubble_tea" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "prix" INTEGER NULL,
    "image" text,
    "icone" text,
    "collection_id" INTEGER REFERENCES "collection"("id"),
    "tea_id" INTEGER REFERENCES "tea"("id"),
    "milk_id" INTEGER REFERENCES "milk"("id"),
    "topping_id" INTEGER REFERENCES "topping"("id"),
    "pearl_id" INTEGER REFERENCES "pearl"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- Ajout de la référence à "bubble_tea" dans la table "collection"
-- Cette étape est nécessaire pour éviter une référence circulaire lors de la création initiale des tables
ALTER TABLE "collection" ADD COLUMN "bubble_tea_id" INTEGER REFERENCES "bubble_tea"("id");

COMMIT;
